# Global
safe:									true
exclude:							[README.md, LICENSE.md, TODO.md, CNAME]
include:							[_categories, _indexes, _pages]
timezone:							Europe/London

# Dependencies
markdown:							kramdown
highlighter:					rouge

# Markdown Processing
kramdown:
  auto_ids:						true
  entity_output:			as_char
  toc_levels:					1..3
  smart_quotes:				lsquo,rsquo,ldquo,rdquo
  input:							GFM
  hard_wrap:					false
  footnote_nr:				1
  footnote_backlink:	▲

# Styling
sass:
  sass_dir:						_sass
  style:							compressed

# Compression
compress_html:
  comments:						all
  clippings:					all
  blanklines:					false

# Permalinks
permalink:						pretty

# Setup
title:								"LifeStack"
byline:								"Training, thoughts, ideas & code"
  
description:					"Tutorials, articles & guidance helping you get the most from technology."
url:									lifestack.io
baseurl:							""
author:
  name:								"LifeStack.io"
  url:								https://github.com/LifeStack-IO
fonts:								"Alegreya:400,400i,700,700i|Baumans|Inconsolata:400,700|Raleway:400,700"

# Collections
collections:
  links:
    output: true
    permalink: /:collection/:path/
  snippets:
    output: true
    permalink: /:collection/:path/
    
# Custom variables
version:							"1.0.8"
read_speed:						160
launched:							"2014"

# Extras
analytics:
  enable:							true
  scroll:							true
  id:									"UA-53673057-1"

github:
  repo:								https://github.com/LifeStack-IO/
  baseurl:						https://github.com/LifeStack-IO/lifestack-io.github.io/tree/master/

social:
  web:								http://lifestack.io
  twitter:						https://twitter.com/LifeStack_IO
  github:							https://github.com/LifeStack-IO