article:
  name: Articles
  description: Articles about how to do things
  lead_image: img/article_leader.svg
  image: img/article_header.svg
  image_fallback: img/article_leader.png

tutorial:
  name: Tutorials
  description: Step-by-step guides to making things happen
  lead_image: img/tutorial_leader.svg
  image: img/tutorial_header.svg
  image_fallback: img/tutorial_leader.png

coding:
  name: Coding
  description: Writings about coding & development
  lead_image: img/coding_leader.svg
  image: img/coding_header.svg
  image_fallback: img/coding_leader.png

google:
  name: Google Apps
  description: Anything & everything about the Google eco-system

chrome:
  name: Chromebooks
  description: Specifically related to using Chromebooks, living a cloud life

blog:
  name: Blogs & Publications
  description: Links to blogs, tutorial sites and other useful publications

tool:
  name: Tools
  description: Hand-picked, road-tested and thoroughly vetted tools

storage:
  name: Cloud Storage Platforms
  description: How our data is stored, and where are the best places to put it

service:
  name: Cloud Services
  description: Manipulating, aggregating, polishing & interpreting data (into information) in an online world
  
education:
  name: Education
  description: Anything with specific educational relevance

training:
  name: Training
  description: Information designed and written to help us all improve, just a little bit